src/Docker/nginx/default.conf

/help now accessible
Accessing /help/ will return to /help

Site now accessible from /help

---

docs/architecture/description/01-architecture-overview.md
docs/architecture/description/02-architecture-context.md
docs/architecture/description/03-architecture-functional.md
docs/architecture/description/04-architecture-process.md
docs/architecture/description/05-architecture-security.md
docs/architecture/description/06-architecture-deployment.md
docs/architecture/description/07-architecture-development.md
docs/architecture/description/08-architecture-testing.md

Fixed a lot of the broken links in the initial sections of the pages
Links to #72

Fixed the links in the ADD that were broken

---

docs/architecture/ADRs/0004_db_migrations.md
docs/architecture/ADRs/0005_login.md
docs/architecture/ADRs/0006_https_certificate.md
docs/architecture/ADRs/0007_deployment_environment.md

Added an ADR for the decision to deploy both the test and production environments into Azure

Added an ADR for the decision about the deployment environment

---

docs/SMG/08-deployment.md
src/Docker/docker-compose.yml

Added instructions for configuring certificates as well as updating the port of the docker compose container

Updated the deployment instructions to include certificates

---

src/API/src/ingest/ingest.module.ts

Fixed missing logger import to module.

Fixed issue with logger from testing refactor

---

.github/workflows/api-pr-build.yml
.github/workflows/ui-pr-build.yml
src/API/package.json
src/UI/jest.config.js

Fixed the branch coverage thresholds.
Fixed the CI builds to run coverage.

Fixed the test coverage for branches as well as triggering coverage in the CI build

---

deployEnvironment.sh
docs/SMG/08-deployment.md
docs/definition-of-done.md
src/API/Dockerfile
src/API/public/feature_flags.json
src/API/src/config/config.controller.test.ts
src/API/src/config/config.controller.ts
src/API/src/config/config.ts
src/Docker/docker-compose.test-local.yml
src/Docker/docker-compose.yml
src/UI/.env.production.template
src/UI/public/googlef6d91c0904d8d267.html
src/generateTokenKey.sh

Added a definition of done as well as setting the default stats flag. I need to work out how to decouple the deployed version from the commited version.

Added a definition of done and set the default value of the stats flag

---

src/UI/public/robots.txt
src/UI/public/sitemap.xml

Added a robots file and a site map with our existing routes. We might need to think about how we maintain the site map.

Added a robots file and a sitemap

---

src/UI/components/map/layers/drawerList.tsx
src/UI/components/map/layers/listButton.tsx
src/UI/components/map/map.test.tsx
src/UI/components/map/map.tsx

Updated the hooks to watch for the right changes in data or the map.

Fixed the flickering on the map by watching for changes in the right hooks

---

src/API/src/schema.gql
src/UI/components/map/layers/__snapshots__/drawerMap.test.tsx.snap
src/UI/components/map/layers/drawerMap.test.tsx
src/UI/components/map/layers/drawerMap.tsx
src/UI/components/map/layers/filters/__snapshots__/downloadList.test.tsx.snap
src/UI/components/map/layers/filters/downloadList.tsx
src/UI/components/map/layers/filters/downloadMap.tsx

Quick change of filtered data button location as mentioned in slack

Moving filtered data button and quick width change

---

docs/SMG/07-maintenance.md

Added docs for secrets

---

src/UI/components/map/layers/downloadDataControl.test.tsx
src/UI/components/map/layers/downloadDataControl.tsx
src/UI/components/map/layers/drawerList.tsx
src/UI/components/map/layers/filters/downloadList.test.tsx
src/UI/components/map/layers/layerControl.tsx
src/UI/components/map/mapView/layerUtils.test.tsx
src/UI/components/map/mapView/layerUtils.tsx
src/UI/state/state.types.ts

Updated the map component to support WMS layers - these have to be manually added to the config for now.

Updated the system to support WMS layers

---

src/API/src/ingest/ingest.controller.ts

Fixed template download location
Links to #386

Fixed template download location

---

src/UI/components/upload/data/Upform.test.tsx
src/UI/state/upload/actions/downloadTemplate.ts
src/UI/state/upload/uploadSlice.tsx

Fixed test

---

.github/workflows/deployment.yml
src/UI/components/datahub/dataHubPanel.tsx
src/UI/components/upload/data/templateDownload.tsx
src/UI/pages/hub.tsx

Fixes a couple of console errors in the UI

Fix/console errors UI

---

src/API/src/db/bionomics/entities/bionomics.entity.ts
src/API/src/db/occurrence/entities/occurrence.entity.ts
src/API/src/schema.gql

Fixed dataset relations

---

src/UI/components/review/ReviewForm.test.tsx
src/UI/components/review/ReviewForm.tsx

Fixed bug in review page

---

src/UI/components/map/mapView/map-v2.tsx
src/UI/components/map/mapView/pointUtils.tsx

overlays changes

---

src/UI/components/map/mapView/downloadImageHandler.tsx

download fix

---

src/API/src/ingest/ingest.service.ts
src/API/src/validation/types/occurrence.validation.ts

Makes dates nullable for occurrence data

Removed nullable validation from occurrence date fields

---

src/UI/state/map/utils/countrySpeciesLists.ts

Added gambiae (S/M) to species list

Added gambiae (S/M) to species list

---

src/API/src/export/utils/convertToCsv.ts

Fixed bug in data ingest when csv creation tries to run on no approved data.

Fixed no-approved-data bug

---

src/API/src/db/insecticideResistance/entities/ace1AlleleFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/ace1GenotypeFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/ace1MethodAndSample.entity.ts
src/API/src/db/insecticideResistance/entities/gsteMethodAndSample.entity.ts
src/API/src/db/insecticideResistance/entities/insecticideResistanceBioassays.entity.ts
src/API/src/db/insecticideResistance/entities/rdl296AlleleFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/rdl296GenotypeFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/rdlMethodAndSample.entity.ts
src/API/src/db/insecticideResistance/entities/vgsc1570AlleleFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/vgsc1570GenotypeFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/vgscGeneytpeFrequencies.entity.ts
src/API/src/db/migrations/1722415160074-more_IR_table_created.ts

Added more IR tables

---

src/API/src/db/bionomics/entities/infection.entity.ts
src/API/src/db/insecticideResistance/entities/ace1AlleleFrequencies.entity.ts
src/API/src/db/insecticideResistance/entities/vgscGeneytpeFrequencies.entity.ts
src/API/src/db/migrations/1723624294330-antoinette_changes.ts

Antoinette changes
